name: Publish dashboard and pixiu aio images

on:
  push:
    branches:
     - "master"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: harbor.cloud.pixiuio.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get short commit hash
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login in harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push dashboard image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/pixiuio/pixiu-dashboard:latest
            ${{ env.REGISTRY }}/pixiuio/pixiu-dashboard:${{ env.COMMIT_HASH }}

      - name: Build and push pixiu aio image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.aio
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/pixiuio/pixiu-aio:latest
            ${{ env.REGISTRY }}/pixiuio/pixiu-aio:${{ env.COMMIT_HASH }}
