name: Publish dashboard image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: echo
      run: echo 1235 `${{ secrets.NAME }}` ${{ secrets.DOCKER_PASSWORD }} ${{ vars.NAME }} dddd

    - name: Login in dockerhub
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push the Docker image
      run: make image && make push
